### ISSUE TITLE
Prayer Prayer and Run orb functionality

### ISSUE THREAD

**Issue by verafeiyd** [Macweese/runelite-external-plugins#1] opened 2024-06-18 06:55 UTC
I would love to see Prayer and Run orb functionality added if possible, thats pretty much it.

**Comment by Macweese** [comment] 2024-06-18 10:32
It is certainly possible to implement your request. However, I'd like to know more about the issue.

To my knowledge, the prayer and run orbs always consume clicks (_Activate Quick-prayer_ and _Toggle run_ are never disabled and are always the first option), compared to the health and special attack orbs which will allow clicks to permeate if e.g. no special attack weapon is equipped or the player is not poisoned/venomed/etc., this is why the functionality was only applied to those specific orbs.

Is there a scenario where the prayer and/or run orbs allow clicks to pass through? Otherwise, have you considered using a plugin e.g. [Custom Menu Swaps](https://github.com/geheur/More-menu-entry-swaps) by Geheur to achieve your desired result? This could be appropriate if your concern is that a menu under the orb is taking priority, e.g. `Attack TzKal-Zuk (level-1400)` is being prioritized over `Activate Quick-prayers`.

**Comment by verafeiyd** [comment] 2024-06-18 23:24
i can actually give an example, when overlapped, i find myself clicking my obelisk in my poh while trying to click the prayer orb and it actually prioritizes the teleport to the fucking wilderness lmao, so yes it would do something, heres a video

[https://i.gyazo.com/dafd5c3f32cf1c3ee521b7ecf7f85ca8.mp4](url)

**Comment by verafeiyd** [comment] 2024-06-18 23:25
but holy shit thank you for that one plugin cop at least, its nice to find one i havent seen yet!

**Comment by verafeiyd** [comment] 2024-07-25 05:50
ive noticed custom menu swaps leads to some weird issues, right click not being clickable sometimes being one of them, would love a no click through run energy option still

**Comment by Macweese** [comment] 2024-07-25 10:40
> ive noticed custom menu swaps leads to some weird issues, right click not being clickable sometimes being one of them, would love a no click through run energy option still

I just checked in game, both on the official client and on RuneLite, and the run energy orb's clickbox doesn't populate the menu with other options. Only the ones for itself, meaning only _Toggle Run_ and _Cancel_ should be available. Are you sure the issue not caused by another plugin? You could try running RuneLite in safe mode to see if it is caused by a plugin-hub plugin.

As for the prayer orb; I can update the plugin to accomodate it as well, similar to the existing orbs.

**Comment by verafeiyd** [comment] 2024-07-25 16:37
nah i just confused myself after a while, sorry lmao. it is the prayer orb kekw

**Comment by Macweese** [comment] 2024-07-25 16:40
Added in aa0623b3920d8c2cebd23964ab89c0aa97a85014

**Closed as completed by Macweese** 2024-07-25 16:40 UTC
Labels: enhancement
